### ISSUE TITLE
Help people have better error messages?

### ISSUE THREAD

**Issue by gabebw** [halogenandtoast/monban#27]
Are you interested in adding this to the README?

```
en:
  activerecord:
    attributes:
      user:
        password_digest: "Password"
```

This would make it so that a presence validation on `:password_digest` would display as `Password can't be blank` instead of `Password digest can't be blank`.
